### ISSUE TITLE
Handle Arrays?

### ISSUE THREAD

**Issue by developit** [fwilkerson/clean-set#1]
Hiya,

Think it'd be worth handling cloning Arrays? Would be a conditional here:
https://github.com/fwilkerson/clean-set/blob/347a4b6247d8bc3bc0df8e6ffc9769fa49cb7a20/lib/index.js#L22

**Comment by fwilkerson** [comment]
Yea definitely, I missed this scenario.

`to = to || !!source.pop ? [] : {}`

I should probably also consider if I actually need `to` as an optional param, or if I should simply set it to an initial value since I never use the second prop of copy.
