### ISSUE TITLE
Updating Multiple Values

### ISSUE THREAD

**Issue by jhwheeler** [fwilkerson/clean-set#8]
First of all, great package! I love the syntax, it's so much terser and easier to read.

I just have one question that I couldn't quite figure out given the info in the docs. Is there a way to update multiple values in one call of `cleanSet()`? 

For example, the equivalent of this:

```js
const food = {
  fruits: ['apples', 'bananas'],
  veggies: ['cucumbers', 'carrots'],
  grains: ['oats'],
}

const myFood = {
  ...food,
  fruits: [...food.fruits, 'mangoes'],
  veggies: [...food.veggies, 'potatoes'],
  drinks: ['smoothies', 'shakes'],
}
```

Thanks in advance!

**Comment by fwilkerson** [comment]
Each key would need it's own `cleanSet` call. For the use case you have above, object spread is preferable. This is really meant for updating a single deeply nested key. Also I've run the esbench on modern browsers and they have come a long way with object spread / object assign performance.

Here's a [link](https://esbench.com/bench/5b16f1cbf2949800a0f61cf2) to the basic benchmark if you want to give it a shot on your machine, but for me chrome 80 blows away `clean-set`. I would have to test this on a really large deeply nested object to see if `clean-set` still has a place, but at least for most people's situation on a modern browser, object assign or object spread is great.

**Comment by jhwheeler** [comment]
Understood, glad to know the use cases.

And yes, I actually ran the benchmarks myself with Chrome 80 after noticing that the linked-to benchmarks were for an older version. To be honest, I was attracted to `clean-set` b/c of the terse syntax -- so I hope we can find a way to get it back up to speed compared to obj spread!

Thank you for your reply. I'll close this as resolved.
